### ISSUE TITLE
IP range improvement request.

### ISSUE THREAD

**Issue by Ryu1254** [lukaszbudnik/keycloak-ip-authenticator#1]
Hello,

I am very new to keycloak, I found your java code to identify the IP address is very interesting. But in your code, we can only specify 1 IP address. is it possible to make it to accept a range of IP instead??

I don't have skill in java.. not sure how to do it.

Thanks

**Comment by lukaszbudnik** [comment]
Sorry, this was meant to be an example only without any (more) complex logic like IP ranges/CIDR blocks.
