### ISSUE TITLE
Cannot locate the keycloak-ip-authenticator.jar correctly

### ISSUE THREAD

**Issue by luojiakickoff** [lukaszbudnik/keycloak-ip-authenticator#2]

**Comment by luojiakickoff** [comment]
Hello

I'm trying to make a custom authentication flow to keycloak by following the README. But after building the keycloak-ip-authenticator.jar by running "mvn package", and trying to copy the jar package to the $KEYCLOAK_HOME/standalone/deployments/, it seem that there was an unexpected file occuring there.

`[root@ip-10-1-10-201 /]# ll opt/keycloak-12.0.4/standalone/deployments/`
`total 24`
`-rw-r--r-- 1 root root 6539 Aug 26 04:17 keycloak-ip-authenticator.jar`
`-rw-r--r-- 1 root root  695 Aug 26 04:17 keycloak-ip-authenticator.jar.failed`
`-rw-r--r-- 1 root root 8888 Mar  1  2021 README.txt`

Does it means that there was something wrong with the keycloak-ip-authenticator.jar?

I'm using the keycloak with the version 12.0.4, which is the same as the one this project used. And do not rewrite the source you have written. 

Have you ever met this situation before,  and could you give me some advice to solve this problem?

Sorry for poor english and thanks in advance.

**Comment by lukaszbudnik** [comment]
I never had this error. 
I have tested it against latest Keycloak running on Quarkus (the only difference is that you copy the jar into `providers` directory) and all is working.
